git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
git clone https://github.com/kien/ctrlp.vim.git $HOME/.vim/bundle/ctrlp.vim
git clone https://github.com/rizzatti/dash.vim.git $HOME/.vim/bundle/dash.vim
git clone git://github.com/mustache/vim-mustache-handlebars.git $HOME/.vim/bundle/mustache
git clone https://github.com/scrooloose/syntastic.git $HOME/.vim/bundle/syntastic
git clone https://github.com/kchmck/vim-coffee-script.git $HOME/.vim/bundle/vim-coffee-script
git clone https://github.com/isRuslan/vim-es6.git $HOME/.vim/bundle/vim-es6
git clone https://github.com/tpope/vim-fugitive.git $HOME/.vim/bundle/vim-fugitive
git clone git@github.com:ledger/vim-ledger.git $HOME/.vim/bundle/vim-ledger
git clone https://github.com/christoomey/vim-tmux-navigator.git $HOME/.vim/bundle/vim-tmux-navigator
git clone git://github.com/wakatime/vim-wakatime.git $HOME/.vim/bundle/vim-wakatime
